### ISSUE TITLE
Select in parameters does not match other inputs style

### ISSUE THREAD

**Issue by eevleevs** [jscad/OpenJSCAD.org#1314]
CSS should include something like 

```css
  #paramsDiv select {
      font-size: 0.85em;
      padding: 0.1em;
  }
```
